### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by deblnia** [UCOpenData/open-data-portal#1]
## To-Do 
- [x] Center welcome text and random fact button
- [x] UChicago random facts
- [ ] Replace articles with Medium pieces

**Comment by sarikam1** [comment]
delegating to self!

**Comment by mercedeswn** [comment]
updating random facts

**Comment by r-e-stern** [comment]
everything that needs centering should be centered now regardless of screen width
